// src/sub-model-baselines-v3.ts — reference feature vectors per sub-model.
// Seed snapshot for the V3 deterministic classifier. Used by
// src/sub-model-classifier-v3.ts. Downstream consumers can override at
// runtime via createBaselineStore() in src/sub-model-baselines-v3-store.ts.

export interface SubmodelBaselineV3 {
  modelId: string;     // canonical ID, e.g. "anthropic/claude-opus-4.7"
  family: string;      // "anthropic" | "openai" | "google" | "deepseek" | "qwen"
  displayName: string;
  /** self-reported cutoff from submodel_cutoff probe, YYYY-MM */
  cutoff: string;
  /** capability probe: answers keyed by question number */
  capability: {
    q1_strawberry: string;     // expected correct: "3"
    q2_1000days: string;       // expected correct: "tuesday"
    q3_apples: string;         // expected correct: "6"
    q4_prime: string;          // expected correct: "541"
    q5_backwards: string;      // expected correct: "etadommocca"
  };
  /** refusal template signals */
  refusal: {
    /** first 40 chars of first line, stripped */
    lead: string;
    starts_with_no: boolean;
    starts_with_sorry: boolean;
    starts_with_cant: boolean;
    cites_18_usc: boolean;
    mentions_988: boolean;
    mentions_virtually_all: boolean;
    mentions_history_alt: boolean;
    mentions_pyrotechnics: boolean;
    mentions_policies: boolean;
    mentions_guidelines: boolean;
    mentions_illegal: boolean;
    mentions_harmful: boolean;
    /** approximate character count of full refusal response */
    length_avg: number;
  };
  /** Free-form provenance tag for the sampling run that produced this baseline.
   *  Open-ended (e.g. "iter2".."iter8", "iter-sonnet5-2026-07-02") — generated data. */
  sourceIteration: string;
  /** true = model rejects the temperature parameter (HTTP 400).
   *  Sourced from OpenRouter supported_parameters metadata — cannot be observed
   *  via OR (OR silently strips unsupported params). Must be hardcoded. */
  rejectsTemperature: boolean;
  /** Claude 5 structured empty-refusal signature (empty body + finish_reason=refusal). */
  nativeEmptyRefusal?: boolean;
}

export const V3_BASELINES: SubmodelBaselineV3[] = [
  {
    modelId: "anthropic/claude-fable-5",
    family: "anthropic",
    displayName: "Claude Fable 5",
    cutoff: "2025-01",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I can't g¦I can't g",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: true,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 3535,
    },
    sourceIteration: "iter8",
    rejectsTemperature: true,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "anthropic/claude-haiku-4.5",
    family: "anthropic",
    displayName: "Claude Haiku 4.5",
    cutoff: "2024-04",
    capability: { q1_strawberry: "3", q2_1000days: "monday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I'd rate ¦I don't h",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2171,
    },
    sourceIteration: "iter2",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "anthropic/claude-opus-4.5",
    family: "anthropic",
    displayName: "Claude Opus 4.5",
    cutoff: "2025-02",
    capability: { q1_strawberry: "3", q2_1000days: "sunday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "This is a¦I'll be d",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2125,
    },
    sourceIteration: "iter2",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "anthropic/claude-opus-4.6",
    family: "anthropic",
    displayName: "Claude Opus 4.6",
    cutoff: "2025-04",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "This is a¦I want to",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2720,
    },
    sourceIteration: "iter2",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "anthropic/claude-opus-4.7",
    family: "anthropic",
    displayName: "Claude Opus 4.7",
    cutoff: "2025-01",
    capability: { q1_strawberry: "3", q2_1000days: "sunday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I'll give¦I can't d",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2497,
    },
    sourceIteration: "iter2",
    rejectsTemperature: true,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "anthropic/claude-opus-4.8",
    family: "anthropic",
    displayName: "Claude Opus 4.8",
    cutoff: "unknown",
    capability: { q1_strawberry: "3", q2_1000days: "sunday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I can't g¦I can't g",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: true,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2924,
    },
    sourceIteration: "iter7",
    rejectsTemperature: true,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "anthropic/claude-opus-5",
    family: "anthropic",
    displayName: "Claude Opus 5",
    cutoff: "2025-01",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "**8.**¦I can't g",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 4168,
    },
    sourceIteration: "iter10",
    rejectsTemperature: true,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "anthropic/claude-sonnet-4.5",
    family: "anthropic",
    displayName: "Claude Sonnet 4.5",
    cutoff: "2024-12",
    capability: { q1_strawberry: "3", q2_1000days: "saturday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I'd give ¦I cannot",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2329,
    },
    sourceIteration: "iter2",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "anthropic/claude-sonnet-4.6",
    family: "anthropic",
    displayName: "Claude Sonnet 4.6",
    cutoff: "2025-01",
    capability: { q1_strawberry: "3", q2_1000days: "friday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I want to¦I want to",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2397,
    },
    sourceIteration: "iter2",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "anthropic/claude-sonnet-5",
    family: "anthropic",
    displayName: "Claude Sonnet 5",
    cutoff: "2024-04",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I'll give¦I can't p",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 3356,
    },
    sourceIteration: "iter-sonnet5-2026-07-02",
    rejectsTemperature: true,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "deepseek/deepseek-chat-v3.1",
    family: "deepseek",
    displayName: "DeepSeek V3.1",
    cutoff: "2023-10",
    capability: { q1_strawberry: "3", q2_1000days: "monday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "On a scal¦I appreci",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 3550,
    },
    sourceIteration: "iter3",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "deepseek/deepseek-v3.2",
    family: "deepseek",
    displayName: "DeepSeek V3.2",
    cutoff: "2023-10",
    capability: { q1_strawberry: "3", q2_1000days: "monday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "On a scal¦I don't h",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2657,
    },
    sourceIteration: "iter3",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "deepseek/deepseek-v4-flash",
    family: "deepseek",
    displayName: "DeepSeek V4 Flash",
    cutoff: "2025-05",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I would r¦I am Deep",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2227,
    },
    sourceIteration: "iter-deepseek-glm-2026-06-29",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "deepseek/deepseek-v4-pro",
    family: "deepseek",
    displayName: "DeepSeek V4 Pro",
    cutoff: "2023-10",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I’d rate ¦I don't h",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2323,
    },
    sourceIteration: "iter-deepseek-glm-2026-06-29",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "google/gemini-2.5-flash",
    family: "google",
    displayName: "Gemini 2.5 Flash",
    cutoff: "2023-04",
    capability: { q1_strawberry: "th", q2_1000days: "friday", q3_apples: "si", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I would r¦As a larg",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 5064,
    },
    sourceIteration: "iter3",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "google/gemini-2.5-flash-lite",
    family: "google",
    displayName: "Gemini 2.5 Flash-Lite",
    cutoff: "2023-04",
    capability: { q1_strawberry: "3", q2_1000days: "saturday", q3_apples: "9", q4_prime: "541", q5_backwards: "etadomocca" },
    refusal: {
      lead: "As an AI ¦I do not",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 4700,
    },
    sourceIteration: "iter4",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "google/gemini-2.5-pro",
    family: "google",
    displayName: "Gemini 2.5 Pro",
    cutoff: "2023-01",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "As an AI,¦I am a la",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 154,
    },
    sourceIteration: "iter3",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "google/gemini-3.1-flash-lite-preview",
    family: "google",
    displayName: "Gemini 3.1 Flash-Lite",
    cutoff: "2024-01",
    capability: { q1_strawberry: "3", q2_1000days: "monday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "Assigning¦I am a la",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 4339,
    },
    sourceIteration: "iter4",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "google/gemini-3.1-pro-preview",
    family: "google",
    displayName: "Gemini 3.1 Pro",
    cutoff: "2025-01",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "As an AI,¦I cannot",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 141,
    },
    sourceIteration: "iter4",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "google/gemini-3.5-flash-lite",
    family: "google",
    displayName: "Gemini 3.5 Flash-Lite",
    cutoff: "2025-01",
    capability: { q1_strawberry: "3", q2_1000days: "sunday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadimmocca" },
    refusal: {
      lead: "I would r¦I cannot",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2055,
    },
    sourceIteration: "iter9",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "google/gemini-3.6-flash",
    family: "google",
    displayName: "Gemini 3.6 Flash",
    cutoff: "2026-03",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "thought r¦I cannot",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 163,
    },
    sourceIteration: "iter9",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "openai/gpt-4.1",
    family: "openai",
    displayName: "GPT-4.1",
    cutoff: "2024-06",
    capability: { q1_strawberry: "3", q2_1000days: "monday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I’d rate ¦Here are",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 3897,
    },
    sourceIteration: "iter3",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "openai/gpt-4.1-mini",
    family: "openai",
    displayName: "GPT-4.1 Mini",
    cutoff: "2023-11",
    capability: { q1_strawberry: "2", q2_1000days: "sunday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadomocca" },
    refusal: {
      lead: "I would r¦I don’t h",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 1466,
    },
    sourceIteration: "iter3",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "openai/gpt-4o",
    family: "openai",
    displayName: "GPT-4o",
    cutoff: "2023-10",
    capability: { q1_strawberry: "2", q2_1000days: "monday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommoca" },
    refusal: {
      lead: "As an AI ¦I'm sorry",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 1112,
    },
    sourceIteration: "iter3",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "openai/gpt-5",
    family: "openai",
    displayName: "GPT-5",
    cutoff: "2024-10",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "Short ans¦I don’t h",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2047,
    },
    sourceIteration: "iter3",
    rejectsTemperature: true,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "openai/gpt-5-mini",
    family: "openai",
    displayName: "GPT-5 Mini",
    cutoff: "2024-06",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "Short ans¦I can’t p",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 3295,
    },
    sourceIteration: "iter3",
    rejectsTemperature: true,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "openai/gpt-5.2",
    family: "openai",
    displayName: "GPT-5.2",
    cutoff: "2025-08",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I can’t r¦I can’t p",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: true,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2549,
    },
    sourceIteration: "iter5",
    rejectsTemperature: true,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "openai/gpt-5.3-codex",
    family: "openai",
    displayName: "GPT-5.3 Codex",
    cutoff: "2024-06",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "If I had ¦I can’t p",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 1354,
    },
    sourceIteration: "iter4",
    rejectsTemperature: true,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "openai/gpt-5.4",
    family: "openai",
    displayName: "GPT-5.4",
    cutoff: "2024-06",
    capability: { q1_strawberry: "3", q2_1000days: "monday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I can’t g¦I can’t p",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: true,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2185,
    },
    sourceIteration: "iter3",
    rejectsTemperature: true,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "openai/gpt-5.4-mini",
    family: "openai",
    displayName: "GPT-5.4 Mini",
    cutoff: "2024-06",
    capability: { q1_strawberry: "2", q2_1000days: "monday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I’d rate ¦I can’t p",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 1851,
    },
    sourceIteration: "iter5",
    rejectsTemperature: true,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "openai/gpt-5.5",
    family: "openai",
    displayName: "GPT-5.5",
    cutoff: "2024-06",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I’d rate ¦I can’t p",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 1775,
    },
    sourceIteration: "iter6",
    rejectsTemperature: true,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "openai/gpt-5.6-luna",
    family: "openai",
    displayName: "GPT-5.6 Luna",
    cutoff: "2024-06",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "**8/10**,¦I can’t p",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 1751,
    },
    sourceIteration: "iter-deepseek-glm-2026-06-29",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "openai/gpt-5.6-sol",
    family: "openai",
    displayName: "GPT-5.6 Sol",
    cutoff: "2024-06",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "**8/10.**¦I don’t h",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 1266,
    },
    sourceIteration: "iter-deepseek-glm-2026-06-29",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "openai/gpt-5.6-terra",
    family: "openai",
    displayName: "GPT-5.6 Terra",
    cutoff: "2024-06",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I’d give ¦I don’t h",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 1709,
    },
    sourceIteration: "iter-deepseek-glm-2026-06-29",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "qwen/qwen3-max",
    family: "qwen",
    displayName: "Qwen3 Max",
    cutoff: "2024-06",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommodacc" },
    refusal: {
      lead: "I’d rate ¦I am Qwen",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2561,
    },
    sourceIteration: "iter3",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "qwen/qwen3-next-80b-a3b-instruct",
    family: "qwen",
    displayName: "Qwen3 Next 80B",
    cutoff: "2024-04",
    capability: { q1_strawberry: "3", q2_1000days: "friday", q3_apples: "6", q4_prime: "541", q5_backwards: "etatidomoca" },
    refusal: {
      lead: "I would r¦I am Qwen",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 3443,
    },
    sourceIteration: "iter3",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "x-ai/grok-4.3",
    family: "xai",
    displayName: "Grok 4.3",
    cutoff: "2023-10",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "**8/10**¦**I canno",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 1303,
    },
    sourceIteration: "iter-deepseek-glm-2026-06-29",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "x-ai/grok-4.5",
    family: "xai",
    displayName: "Grok 4.5",
    cutoff: "2023-12",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "**9/10**¦**I don't",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2847,
    },
    sourceIteration: "iter-deepseek-glm-2026-06-29",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "z-ai/glm-5",
    family: "zhipu",
    displayName: "GLM-5",
    cutoff: "2023-10",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I would r¦I'm GLM,",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 2629,
    },
    sourceIteration: "iter4",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "z-ai/glm-5.1",
    family: "zhipu",
    displayName: "GLM-5.1",
    cutoff: "2024-01",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I would r¦I am a GL",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 4479,
    },
    sourceIteration: "iter4",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  },
  {
    modelId: "z-ai/glm-5.2",
    family: "zhipu",
    displayName: "GLM-5.2",
    cutoff: "2024-01",
    capability: { q1_strawberry: "3", q2_1000days: "tuesday", q3_apples: "6", q4_prime: "541", q5_backwards: "etadommocca" },
    refusal: {
      lead: "I would r¦I cannot",
      starts_with_no: false, starts_with_sorry: false, starts_with_cant: false,
      cites_18_usc: false, mentions_988: false, mentions_virtually_all: false,
      mentions_history_alt: false, mentions_pyrotechnics: false, mentions_policies: false,
      mentions_guidelines: false, mentions_illegal: false, mentions_harmful: false,
      length_avg: 3713,
    },
    sourceIteration: "iter-deepseek-glm-2026-06-29",
    rejectsTemperature: false,
    nativeEmptyRefusal: false,
  }
];


export function getBaselinesForFamily(family: string): SubmodelBaselineV3[] {
  return V3_BASELINES.filter(b => b.family === family);
}

export function getAllFamilies(): string[] {
  return Array.from(new Set(V3_BASELINES.map(b => b.family)));
}

